### PR TITLE
fix: declare correct gencode version in v7 proto stubs for protobuf 7.x (#11548)

### LINKED ISSUE #11548: [Bug]: wandb doesn't work with `protobuf>=7.34.0`
### Describe the bug

The current version of `protobuf` does not support the latest versions of `protobuf` (>=7.34.0):
```
 ImportError: cannot import name 'Imports' from 'wandb.proto.wandb_telemetry_pb2' (/build/source/wandb/proto/wandb_telemetry_pb2.py)
```
I tried regenerating the `wandb_api_pb2.py` file but I couldn't make it work.

### PR DESCRIPTION
**Pull request by gambletan**
## Summary

Fixes the protobuf >= 7.34.0 incompatibility reported in #11548.

The `wandb/proto/v7/` pb2 files were copied from `v6/` but their
`ValidateProtobufRuntimeVersion` calls still declared gencode version
`6.31.1`. When users install `protobuf >= 7.34.0` the dispatch wrapper
correctly routes to the `v7/` subpackage, but the gencode/runtime major
mismatch (6 vs 7) is semantically wrong and could cause `VersionError`
if protobuf adds stricter cross-major validation in a future release.

Additionally, `v5/`, `v6/`, and `v7/` were missing `__init__.py` (only
`v4/` had one), and `wandb_generate_proto.py` never created `__init__.py`
for newly generated version subdirectories.

**Changes:**

- Update `ValidateProtobufRuntimeVersion` in all 7 `v7/` pb2 files to
  declare gencode version `7.0.0` (correct for the protobuf 7.x runtime).
- Update the `# Protobuf Python Version:` header comment to `7.0.0`.
- Add missing `__init__.py` to `wandb/proto/v5/`, `v6/`, and `v7/` so
  each is an explicit Python package (matching `v4/`).
- Fix `wandb_generate_proto.py` to create `__init__.py` when it generates
  a new version subdirectory, preventing this from recurring for v8+.
- Add `tests/unit_tests/test_proto_version_compat.py` with 14 tests
  covering proto import smoke tests, v7 structure validation, and
  `__init__.py` presence for all version subdirs.

## Test plan

- [x] `tests/unit_tests/test_proto_version_compat.py` — 14 new tests, all passing with `protobuf==7.34.1`
- [x] Manually verified `from wandb.proto.wandb_telemetry_pb2 import Imports` succeeds with `protobuf==7.34.1`
- [x] Verified `ValidateProtobufRuntimeVersion(PUBLIC, 7, 0, 0)` passes with `protobuf==7.34.1` runtime

Closes #11548

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by dmitryduev** [comment]
Addressed in #11580 in a more general way.
