### ISSUE TITLE
[Bug]: wandb doesn't work with `protobuf>=7.34.0`

### ISSUE THREAD

**Issue by GaetanLepage** [wandb/wandb#11548]
### Describe the bug

The current version of `protobuf` does not support the latest versions of `protobuf` (>=7.34.0):
```
 ImportError: cannot import name 'Imports' from 'wandb.proto.wandb_telemetry_pb2' (/build/source/wandb/proto/wandb_telemetry_pb2.py)
```
I tried regenerating the `wandb_api_pb2.py` file but I couldn't make it work.

**Comment by GaetanLepage** [comment]
Sorry, missed the comment. It does this wandb for us, thanks a lot!
