### ISSUE TITLE
[Bug]: wandb doesn't work with protobuf==6.30.2

### ISSUE THREAD

**Issue by deep1401** [wandb/wandb#9674]
### Describe the bug

Trying to import wandb when I have protobuf 6.30.2 gives this error. I need to be on this protobuf version due to dependencies of other packages.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deep.gandhi/.transformerlab/envs/transformerlab/lib/python3.11/site-packages/wandb/__init__.py", line 22, in <module>
    from wandb.sdk.lib import wb_logging as _wb_logging
  File "/Users/deep.gandhi/.transformerlab/envs/transformerlab/lib/python3.11/site-packages/wandb/sdk/__init__.py", line 24, in <module>
    from . import wandb_helper as helper
  File "/Users/deep.gandhi/.transformerlab/envs/transformerlab/lib/python3.11/site-packages/wandb/sdk/wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "/Users/deep.gandhi/.transformerlab/envs/transformerlab/lib/python3.11/site-packages/wandb/sdk/lib/__init__.py", line 2, in <module>
    from .disabled import RunDisabled, SummaryDisabled
  File "/Users/deep.gandhi/.transformerlab/envs/transformerlab/lib/python3.11/site-packages/wandb/sdk/lib/disabled.py", line 3, in <module>
    from wandb.sdk.lib import deprecate
  File "/Users/deep.gandhi/.transformerlab/envs/transformerlab/lib/python3.11/site-packages/wandb/sdk/lib/deprecate.py", line 7, in <module>
    from wandb.proto.wandb_telemetry_pb2 import Deprecated as TelemetryDeprecated
ImportError: cannot import name 'Deprecated' from 'wandb.proto.wandb_telemetry_pb2' (/Users/deep.gandhi/.transformerlab/envs/transformerlab/lib/python3.11/site-packages/wandb/proto/wandb_telemetry_pb2.py)
```

**Comment by luisbergua** [comment]
Hey @deep1401, thanks for your answer! I was able to reproduce this with `wandb --version`, will raise with our engineers

**Comment by vantienpham** [comment]
I ran into the same error with wandb version 0.25.0

```bash
(pytorch-2.6) [van-tien.pham@sms-cluster sclip]$ pip install --user --no-cache-dir wandb
Requirement already satisfied: wandb in /home/van-tien.pham/.local/lib/python3.11/site-packages (0.25.0)
Requirement already satisfied: click>=8.0.1 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from wandb) (8.3.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from wandb) (3.1.46)
Requirement already satisfied: packaging in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from wandb) (24.2)
Requirement already satisfied: platformdirs in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from wandb) (4.3.7)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from wandb) (6.30.2)
Requirement already satisfied: pydantic<3 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from wandb) (2.12.5)
Requirement already satisfied: pyyaml in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from wandb) (6.0.2)
Requirement already satisfied: requests<3,>=2.0.0 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from wandb) (2.32.3)
Requirement already satisfied: sentry-sdk>=2.0.0 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from wandb) (2.53.0)
Requirement already satisfied: typing-extensions<5,>=4.8 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from wandb) (4.15.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: annotated-types>=0.6.0 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from pydantic<3->wandb) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from pydantic<3->wandb) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (2025.1.31)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.2)
(pytorch-2.6) [van-tien.pham@sms-cluster sclip]$ wandb
Traceback (most recent call last):
  File "/home/van-tien.pham/.local/bin/wandb", line 5, in <module>
    from wandb.cli.cli import cli
  File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/__init__.py", line 22, in <module>
    from wandb.sdk.lib import wb_logging as _wb_logging
  File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/sdk/__init__.py", line 24, in <module>
    from . import wandb_helper as helper
  File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/sdk/wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/sdk/lib/config_util.py", line 10, in <module>
    from wandb.util import load_yaml
  File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/util.py", line 51, in <module>
    from wandb.sdk.lib import filesystem, runid
  File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/sdk/lib/filesystem.py", line 19, in <module>
    from wandb.sdk.wandb_settings import Settings
  File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/sdk/wandb_settings.py", line 38, in <module>
    from wandb.proto import wandb_settings_pb2
  File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/proto/wandb_settings_pb2.py", line 12, in <module>
    from wandb.proto.v6.wandb_settings_pb2 import *
  File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/proto/v6/wandb_settings_pb2.py", line 12, in <module>
    _runtime_version.ValidateProtobufRuntimeVersion(
  File "/public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages/google/protobuf/runtime_version.py", line 113, in ValidateProtobufRuntimeVersion
    _ReportVersionError(
  File "/public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages/google/protobuf/runtime_version.py", line 50, in _ReportVersionError
    raise VersionError(msg)
google.protobuf.runtime_version.VersionError: Detected incompatible Protobuf Gencode/Runtime versions when loading wandb/proto/wandb_settings.proto: gencode 6.31.1 runtime 6.30.2. Runtime version cannot be older than the linked gencode version. See Protobuf version guarantees at https://protobuf.dev/support/cross-version-runtime-guarantee.
```

**Comment by vantienpham** [comment]
> I ran into the same error with wandb version 0.25.0
> 
> (pytorch-2.6) [van-tien.pham@sms-cluster sclip]$ pip install --user --no-cache-dir wandb
> Requirement already satisfied: wandb in /home/van-tien.pham/.local/lib/python3.11/site-packages (0.25.0)
> Requirement already satisfied: click>=8.0.1 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from wandb) (8.3.1)
> Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from wandb) (3.1.46)
> Requirement already satisfied: packaging in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from wandb) (24.2)
> Requirement already satisfied: platformdirs in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from wandb) (4.3.7)
> Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from wandb) (6.30.2)
> Requirement already satisfied: pydantic<3 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from wandb) (2.12.5)
> Requirement already satisfied: pyyaml in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from wandb) (6.0.2)
> Requirement already satisfied: requests<3,>=2.0.0 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from wandb) (2.32.3)
> Requirement already satisfied: sentry-sdk>=2.0.0 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from wandb) (2.53.0)
> Requirement already satisfied: typing-extensions<5,>=4.8 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from wandb) (4.15.0)
> Requirement already satisfied: gitdb<5,>=4.0.1 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
> Requirement already satisfied: annotated-types>=0.6.0 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from pydantic<3->wandb) (0.7.0)
> Requirement already satisfied: pydantic-core==2.41.5 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from pydantic<3->wandb) (2.41.5)
> Requirement already satisfied: typing-inspection>=0.4.2 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from pydantic<3->wandb) (0.4.2)
> Requirement already satisfied: charset-normalizer<4,>=2 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (3.4.1)
> Requirement already satisfied: idna<4,>=2.5 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (3.10)
> Requirement already satisfied: urllib3<3,>=1.21.1 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (2.4.0)
> Requirement already satisfied: certifi>=2017.4.17 in /public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (2025.1.31)
> Requirement already satisfied: smmap<6,>=3.0.1 in /home/van-tien.pham/.local/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.2)
> (pytorch-2.6) [van-tien.pham@sms-cluster sclip]$ wandb
> Traceback (most recent call last):
>   File "/home/van-tien.pham/.local/bin/wandb", line 5, in <module>
>     from wandb.cli.cli import cli
>   File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/__init__.py", line 22, in <module>
>     from wandb.sdk.lib import wb_logging as _wb_logging
>   File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/sdk/__init__.py", line 24, in <module>
>     from . import wandb_helper as helper
>   File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/sdk/wandb_helper.py", line 6, in <module>
>     from .lib import config_util
>   File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/sdk/lib/config_util.py", line 10, in <module>
>     from wandb.util import load_yaml
>   File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/util.py", line 51, in <module>
>     from wandb.sdk.lib import filesystem, runid
>   File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/sdk/lib/filesystem.py", line 19, in <module>
>     from wandb.sdk.wandb_settings import Settings
>   File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/sdk/wandb_settings.py", line 38, in <module>
>     from wandb.proto import wandb_settings_pb2
>   File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/proto/wandb_settings_pb2.py", line 12, in <module>
>     from wandb.proto.v6.wandb_settings_pb2 import *
>   File "/home/van-tien.pham/.local/lib/python3.11/site-packages/wandb/proto/v6/wandb_settings_pb2.py", line 12, in <module>
>     _runtime_version.ValidateProtobufRuntimeVersion(
>   File "/public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages/google/protobuf/runtime_version.py", line 113, in ValidateProtobufRuntimeVersion
>     _ReportVersionError(
>   File "/public/conda/Miniconda/envs/pytorch-2.6/lib/python3.11/site-packages/google/protobuf/runtime_version.py", line 50, in _ReportVersionError
>     raise VersionError(msg)
> google.protobuf.runtime_version.VersionError: Detected incompatible Protobuf Gencode/Runtime versions when loading wandb/proto/wandb_settings.proto: gencode 6.31.1 runtime 6.30.2. Runtime version cannot be older than the linked gencode version. See Protobuf version guarantees at https://protobuf.dev/support/cross-version-runtime-guarantee.

Fixed with `pip install --user --no-cache-dir protobuf==6.33.5`.
