### PR TITLE
chore: add protobuf v7 support

### LINKED ISSUE #11548: [Bug]: wandb doesn't work with `protobuf>=7.34.0`
### Describe the bug

The current version of `protobuf` does not support the latest versions of `protobuf` (>=7.34.0):
```
 ImportError: cannot import name 'Imports' from 'wandb.proto.wandb_telemetry_pb2' (/build/source/wandb/proto/wandb_telemetry_pb2.py)
```
I tried regenerating the `wandb_api_pb2.py` file but I couldn't make it work.

### PR DESCRIPTION
**Pull request by dmitryduev**
Description
-----------
Fixes #11548.

Following a nice tradition, grpc-tools is lagging behind major protobuf releases, so this may or may not be 100% correct, but for now makes wandb work with protobuf v7 as far as I can tell.

TODO: We should recreate the bindings once grpc-tools catches up.

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Thanks a lot! This seems to work great!
It would be highly helpful for us (nixpkgs packagers) if this PR would be merged and released (maybe as a patch release).

Anyways, thanks a lot for your reactivity!

**Comment by dmitryduev** [comment]
### Merge activity

* **Mar 23, 5:52 PM UTC**: [Graphite](https://app.graphite.com/github/pr/wandb/wandb/11552) couldn't merge this PR because it was not satisfying all requirements (Failed CI: 'ci/circleci: system-tests-min-server-version-linux-3.13').
